
import { Course, UniversityProfile, HelpdeskContact } from './types';

export const COURSE_DB: Course[] = [
  {
    course_name: "BSc CA IT Honours",
    spoken_name: "Bachelor of Science in Computer Applications and Information Technology Honours",
    department: "computer science",
    duration_years: 4,
    fees_yearly: 70000,
    aliases: ["bsc ca it", "b sc ca it", "computer applications", "computer it"],
    description: "Undergraduate program focused on computer applications, IT fundamentals, and software development.",
    eligibility: "10+2 with Maths, Commerce, or Computer-related subjects",
  },
  {
    course_name: "BSc IT Honours Cyber Security",
    spoken_name: "Bachelor of Science in Information Technology Honours in Cyber Security",
    department: "computer science",
    duration_years: 4,
    fees_yearly: 85000,
    aliases: ["bsc it cyber security", "cyber security", "it cyber"],
    description: "Specialized undergraduate program focused on cyber security, digital forensics, and network defense.",
    eligibility: "10+2 with Maths or Computer-related subjects",
  },
  {
    course_name: "BSc IT Honours Data Science",
    spoken_name: "Bachelor of Science in Information Technology Honours in Data Science",
    department: "computer science",
    duration_years: 4,
    fees_yearly: 75000,
    aliases: ["bsc it data science", "data science"],
    description: "Undergraduate program focused on data analytics, statistics, and artificial intelligence foundations.",
    eligibility: "10+2 with Maths or Statistics",
  },
  {
    course_name: "Bachelor of Computer Applications",
    spoken_name: "Bachelor of Computer Applications",
    department: "computer science",
    duration_years: 4,
    fees_yearly: 70000,
    aliases: ["bca", "computer applications"],
    description: "Professional undergraduate program focused on software development, web technologies, and computer fundamentals.",
    eligibility: "10+2 in any stream with English",
  },
  {
    course_name: "Master of Computer Applications",
    spoken_name: "Master of Computer Applications",
    department: "computer science",
    duration_years: 2,
    fees_yearly: 140000,
    aliases: ["mca", "masters in computer applications"],
    description: "Postgraduate program designed to build professional careers in computer science and information technology.",
    eligibility: "BCA / BE / B.Sc. (CS/IT) or equivalent",
  },
  {
    course_name: "MSc CA IT",
    spoken_name: "Master of Science in Computer Applications and Information Technology",
    department: "computer science",
    duration_years: 2,
    fees_yearly: 75000,
    aliases: ["msc ca it", "msc it"],
    description: "Postgraduate program focused on advanced computing, software systems, and IT applications.",
    eligibility: "BCA, B.Sc. (CS/IT), BIT, BE (CE/IT), PGDCA or equivalent",
  },
  {
    course_name: "MSc IT Cyber Security",
    spoken_name: "Master of Science in Information Technology with Cyber Security specialization",
    department: "computer science",
    duration_years: 2,
    fees_yearly: 100000,
    aliases: ["msc it cyber security", "masters cyber security"],
    description: "Postgraduate specialization focused on cyber security, digital forensics, and information security management.",
    eligibility: "Any Science graduate (bridge course required for non-maths background)",
  },
  {
    course_name: "MSc IT Data Science",
    spoken_name: "Master of Science in Information Technology with Data Science specialization",
    department: "computer science",
    duration_years: 2,
    fees_yearly: 100000,
    aliases: ["msc it data science", "masters data science"],
    description: "Postgraduate program focused on data science, machine learning, analytics, and big data technologies.",
    eligibility: "BCA / B.Sc. (CS/IT/Data Science) or equivalent",
  },
];

export const UNIVERSITY_PROFILE: UniversityProfile = {
  university_name: "Ganpat University",
  official_short_name: "GUNI",
  type_legal_status: "State Private, Not-for-profit University (established by Gujarat State Legislature).",
  act_establishment: "Established under The Ganpat University Act, 2005 (Gujarat Act No. 19 of 2005).",
  location_address: "Ganpat Vidyanagar, Mehsana–Gandhinagar Highway, PO – 384012, Kherva / Mehsana, North Gujarat, India.",
  campus_size: "Approximately 300 acres.",
  accreditation_naac: "NAAC A Grade.",
  ugc_recognition: "Recognized by UGC; listed under Section 2(f) of the UGC Act, 1956.",
  memberships_affiliations: "AIU (Association of Indian Universities), UGC.",
  president_patron: "Shri Ganpatbhai (Ganpat) Patel — Patron-in-Chief & President.",
  director_general: "Dr. Mahendra Sharma.",
  student_strength: "Approximately 25,000+ students.",
  faculty_staff: "Faculty ~700+; total staff ~1000+.",
  major_schools: "Multiple constituent institutes including Engineering, Technology, Management, Pharmacy, Marine, Nursing, Computer Applications, Design and Architecture.",
  core_offerings: "Diploma, UG, PG, integrated programs, professional courses, Ph.D., marine and technical programs, certificate and skill programs.",
  rankings_ratings: "GSIRF 5-Star overall rating; QS I-Gauge recognitions and other awards.",
  achievements_awards: "NAAC A Grade; recognized as a Center of Excellence by Gujarat Government; QS I-Gauge ratings; CAREEdge NGO 2A grading.",
  official_website: "https://www.ganpatuniversity.ac.in",
  admissions_portal: "https://admission.ganpatuniversity.ac.in",
  international_admissions: "https://international.ganpatuniversity.ac.in",
  contact_phone: "+91-2762-226000 / +91-2762-286080; Toll Free: 1800 233 12345; Admissions: +91-81006-16161",
  contact_email: "info@ganpatuniversity.ac.in",
  international_email: "int.admission@ganpatuniversity.ac.in",
  alumni_count: "More than 25,000 students have graduated.",
  research_incubation: "Centre for Advanced Research Studies, incubation and innovation centres, ARIIA/IIC activities.",
  notes: "Refer to official reports for the latest figures.",
};

export const HELPDESK_DB: HelpdeskContact[] = [
  {
    institute_name: "Department of Computer Science (DCS)",
    contact_person_1: "Dhaval Prajapati",
    contact_person_2: "Hemant Patel",
    phone_number_1: "9979568608",
    phone_number_2: "7486922232",
    email: "",
    whatsapp_number: "9979568608",
    office_timings: "9:00 AM to 5:30 PM",
  },
  {
    institute_name: "AMPICS – BCA",
    contact_person_1: "Saraswatiben Patel",
    contact_person_2: "Hemant Patel",
    phone_number_1: "9428459589",
    phone_number_2: "7486922232",
    email: "",
    whatsapp_number: "9428459589",
    office_timings: "9:00 AM to 5:30 PM",
  },
  {
    institute_name: "AMPICS – MCA",
    contact_person_1: "Pankaj Patel",
    contact_person_2: "Hemant Patel",
    phone_number_1: "9428666068",
    phone_number_2: "7486922232",
    email: "",
    whatsapp_number: "7486922232",
    office_timings: "9:00 AM to 5:30 PM",
  },
];
